version: "3"
services:
  web:
    build:
       context: .
       dockerfile: app.Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    ports:
     - "1400:1433"
    